Retreive name from kwargs in LunaryCallbackHandler.on_retriever_start
fix: handle missing `name` in `on_retriever_start`

Resolved the error:
`ERROR:lunary:An error occurred in 'on_retriever_start': 'NoneType' object has no attribute 'get'`.

The issue occurred because `langchain_core` sends `name` in `callback_manager.on_retriever_start`, and serialized as None

Fix implemented by adding the `name` parameter to `on_retriever_start`